# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.4-rhel
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-08-29T06:27:42Z"
  labels:
    app: dns-pod
  name: dns-pod
spec:
  restartPolicy: Always
  containers:
  - env:
    - name: PDNS_AUTH_API_KEY
      value: secret
    image: docker.io/powerdns/pdns-auth-master:48-lmdb-index-1
    name: auth
    ports:
    - containerPort: 1053
      hostPort: 53
    - containerPort: 8053
      hostPort: 8053
    - containerPort: 80
      hostPort: 80
    - containerPort: 9091
      hostPort: 9091
    - containerPort: 1053
      hostPort: 53
      protocol: UDP
    - containerPort: 8053
      hostPort: 8053
      protocol: UDP
    securityContext: {}
    volumeMounts:
    - mountPath: /var/lib/powerdns
      name: opt-powerdns-pod-data-powerdns-auth-host-0
    - mountPath: /etc/powerdns/pdns.d/pdns.conf
      name: opt-powerdns-pod-pdns.d-pdns.conf-host-1
      readOnly: true
    image: docker.io/powerdns/pdns-recursor-master:experimental-bullseye-upgrade-1
    name: recursor
    securityContext: {}
    volumeMounts:
    - mountPath: /etc/powerdns/recursor.conf
      name: opt-powerdns-pod-recursor.d-recursor.conf-host-0
      readOnly: true
  - args:
    - gunicorn
    - powerdnsadmin:create_app()
    env:
    - name: GUNICORN_LOGLEVEL
      value: INFO
    - name: SQLALCHEMY_DATABASE_URI
      value: sqlite:////data/admin.sqlite
    - name: GUNICORN_workers
      value: "2"
    - name: GUNICORN_TIMEOUT
      value: "60"
    image: docker.io/ngoduykhanh/powerdns-admin:v0.3.0
    name: admin
    securityContext: {}
    volumeMounts:
    - mountPath: /data/admin.sqlite
      name: opt-powerdns-pod-data-powerdns-admin-admin.sqlite-host-0
  volumes:
  - hostPath:
      path: /opt/powerdns-pod/data/powerdns-admin/admin.sqlite
      type: File
    name: opt-powerdns-pod-data-powerdns-admin-admin.sqlite-host-0
  - hostPath:
      path: /opt/powerdns-pod/data/powerdns-auth/
      type: File
    name: opt-powerdns-pod-data-powerdns-auth-host-0
  - hostPath:
      path: /opt/powerdns-pod/pdns.d/pdns.conf
      type: File
    name: opt-powerdns-pod-pdns.d-pdns.conf-host-1
  - hostPath:
      path: /opt/powerdns-pod/recursor.d/recursor.conf
      type: File
    name: opt-powerdns-pod-recursor.d-recursor.conf-host-0
